services:
  db:  
    image : postgres:11.21-bullseye
    ports:
      - 5432:5432
    volumes:
      - ./docker-dev-volumes/postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
  urn_nbn_backend:
    build: 
      context: .
      dockerfile: Dockerfile-dev-urn-nbn
    tty: true
    command: ["uvicorn", "main:app", "--reload","--host", "0.0.0.0", "--port", "10124"]
    volumes:
      - ./app_urn_nbn:/home/akmi/urn-nbn
      - /home/akmi/urn-nbn/data
      - /home/akmi/urn-nbn/logs
    ports:
      - 85:10124
    environment:
      - DB_DIALECT=postgresql
      - DB_URL=//postgres:postgres@host.docker.internal:5432/db
    depends_on:
      - db
  urn_nbn_admin:
    build:
      context: .
      dockerfile : Dockerfile-dev-urn-nbn-admin
    tty : true
    command : "npm run dev"
    environment:
      - BASE_URL=http://localhost:81
      - POETRY_VIRTUALENVS_CREATE=false
    volumes:
      - ./urn_nbn_admin:/app
      - /app/node_modules
    ports:
      - 83:3000
    depends_on:
      - db 