FROM python:3.13-bookworm
LABEL authors="akmi"

ARG VERSION=0.1.0

# Combine apt-get commands to reduce layers
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get dist-upgrade -y && \
    apt-get install -y git curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Install Poetry using the official installation script
RUN curl -sSL https://install.python-poetry.org | python3 -

# Add Poetry to the PATH
ENV PATH="/root/.local/bin:$PATH"

RUN useradd -ms /bin/bash akmi


WORKDIR /home/akmi
ENV PYTHONPATH=/home/akmi/urn-nbn/src
ENV BASE_DIR=/home/akmi/urn-nbn
RUN mkdir -p  ${BASE_DIR}/data ${BASE_DIR}/logs
RUN chmod 777 -R ${BASE_DIR}/data 
RUN chmod 777 -R ${BASE_DIR}/logs 
WORKDIR ${BASE_DIR}
COPY ./app_urn_nbn/pyproject.toml .
COPY ./app_urn_nbn/README.md .
# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    POETRY_VERSION=1.6.1 \
    POETRY_HOME=/opt/poetry \
    PATH="/opt/poetry/bin:$PATH" \
    VIRTUAL_ENV=/opt/venv \
    PATH="/opt/venv/bin:$PATH"
# Buat virtual environment
RUN python -m venv $VIRTUAL_ENV

RUN pip install psycopg2

RUN  poetry install --no-root --only main
USER akmi
WORKDIR ${BASE_DIR}